main:
  user: root
  hostname: privacysandboxdemos.domain-aaa.com
  deploy_path: /home/rtcamp/global-services/privacysandboxdemos

ci:
  user: root
  hostname: privacysandboxdemos.domain-aaa.com
  deploy_path: /home/rtcamp/global-services/privacysandboxdemos
